# Generated by Django 3.2.16 on 2023-06-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('Student', 'Student'), ('Basic', 'Basic'), ('Premium', 'Premium'), ('Ultra', 'Ultra')], max_length=20, unique=True),
        ),
    ]
